profile                  = ""
environment              = "development"
env_subtype              = ""
subdomain                = "replaceme"
infrastructure_cicd_role = "dl-aws-wlnp-dev-ipa-infcicd"
workload_cicd_role       = "dl-aws-wlnp-dev-ipa-wlcicd"
